### ISSUE TITLE
twitterプラグインだけ抜いた状態でつけっぱなしにすると落ちる

### ISSUE THREAD

**Issue by kazu0617** [mikutter/mikutter#11]
# 概要
タイトル通りです。
core/plugin/twitterを抜いた状態にて、長い間つけっぱなしにしておくと突然落ちます。
--debugをつけない状態では何も出なかったため、--debugをつけて放っておいた所、以下の様なログを出力しました。
```
error: {MIKUTTER_DIR}/core/serialthread.rb:83:in `rescue in block in new_thread': uninitialized constant MikuTwitter
Did you mean?  Mikutter
from {MIKUTTER_DIR}/core/plugin/api_request_file_cache.rb:7:in `gc'
from {MIKUTTER_DIR}/core/plugin/api_request_file_cache.rb:12:in `block (2 levels) in <top (required)>'
from {MIKUTTER_DIR}/core/serialthread.rb:70:in `block in new_thread'
notice: mikutter/mikutter.rb:75:in `rescue in boot!': catch exception `SystemExit'
notice: mikutter/mikutter.rb:77:in `rescue in boot!': => `SystemExit'
notice: mikutter/mikutter.rb:109:in `rescue in <main>': catch SystemExit
```

# 環境
- 対象バージョン: 3.8
- クラッシュする: Yes

## plugin(core)
- core/plugin/twitterを除去
- core/plugin/searchからtwitter-hashtag関連の挙動を削除( [ｺｺ](https://github.com/mikutter/mikutter/blob/d441aa5acd93080caeb9aea67317c142495d4bc1/core/plugin/search/search.rb#L10-L12)を消す ) / .mikutter.ymlから依存関係としてtwitterを除去
(worldonプラグインにsearchが依存プラグインとして挙げられていたため)

## plugin(general)
```
display_requirements.rb  mikutter_justsize              sub_parts_client
fcm                      mikutter_sub_parts_image_flex  twemoji
mikutter-uwm-hommage     mikutter_subparts_nsfw         worldon
mikutter_fcmnotify       show_tweet                     worldon_remote_emoji
```

**Comment by kazu0617** [comment]
先ほどRedmineのほうに[転記しました](https://dev.mikutter.hachune.net/issues/1295)ので、こちらはCloseします。
