### ISSUE TITLE
mikutter wont start anymore after Update

### ISSUE THREAD

**Issue by JPRuehmann** [mikutter/mikutter#5]
After I´ve Updated mikutter today I only get the following errors.
```
/usr/lib/ruby/2.3.0/psych.rb:471:in `initialize': Datei oder Verzeichnis nicht gefunden @ rb_sysopen - /var/lib/gems/2.3.0/gems/twitter-text-1.14.3/lib/assets/tld_lib.yml (Errno::ENOENT)
        from /usr/lib/ruby/2.3.0/psych.rb:471:in `open'
        from /usr/lib/ruby/2.3.0/psych.rb:471:in `load_file'
        from /var/lib/gems/2.3.0/gems/twitter-text-1.14.3/lib/twitter-text/regex.rb:29:in `<class:Regex>'
        from /var/lib/gems/2.3.0/gems/twitter-text-1.14.3/lib/twitter-text/regex.rb:8:in `<module:Twitter>'
        from /var/lib/gems/2.3.0/gems/twitter-text-1.14.3/lib/twitter-text/regex.rb:3:in `<top (required)>'
        from /var/lib/gems/2.3.0/gems/twitter-text-1.14.3/lib/twitter-text.rb:21:in `require'
        from /var/lib/gems/2.3.0/gems/twitter-text-1.14.3/lib/twitter-text.rb:21:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/twitter-text-1.14.3/lib/twitter-text.rb:20:in `each'
        from /var/lib/gems/2.3.0/gems/twitter-text-1.14.3/lib/twitter-text.rb:20:in `<top (required)>'
        from /home/ruehmann/mikutter/core/mui/gtk_postbox.rb:9:in `require'
        from /home/ruehmann/mikutter/core/mui/gtk_postbox.rb:9:in `<top (required)>'
        from /home/ruehmann/mikutter/core/miquire.rb:98:in `require'
        from /home/ruehmann/mikutter/core/miquire.rb:98:in `miquire_original_require'
        from /home/ruehmann/mikutter/core/miquire.rb:95:in `file_or_directory_require'
        from /home/ruehmann/mikutter/core/miquire.rb:76:in `block in miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in `each'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in `miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:18:in `miquire'
        from /home/ruehmann/mikutter/core/mui/cairo_timeline.rb:9:in `<top (required)>'
        from /home/ruehmann/mikutter/core/miquire.rb:98:in `require'
        from /home/ruehmann/mikutter/core/miquire.rb:98:in `miquire_original_require'
        from /home/ruehmann/mikutter/core/miquire.rb:95:in `file_or_directory_require'
        from /home/ruehmann/mikutter/core/miquire.rb:76:in `block in miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in `each'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in `miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:18:in `miquire'
        from /home/ruehmann/mikutter/core/mui/cairo_inner_tl.rb:3:in `<top (required)>'
        from /home/ruehmann/mikutter/core/miquire.rb:98:in `require'
        from /home/ruehmann/mikutter/core/miquire.rb:98:in `miquire_original_require'
        from /home/ruehmann/mikutter/core/miquire.rb:95:in `file_or_directory_require'
        from /home/ruehmann/mikutter/core/miquire.rb:76:in `block in miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in `each'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in `miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:18:in `miquire'
        from /home/ruehmann/mikutter/core/plugin/gtk/gtk.rb:7:in `<top (required)>'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:155:in `load'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:155:in `load'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:148:in `block in load'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:146:in `each'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:146:in `load'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:148:in `block in load'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:146:in `each'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:146:in `load'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:98:in `block in load_all'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:38:in `block in each_spec'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:33:in `each'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:33:in `each'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:36:in `each_spec'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:96:in `load_all'
        from /home/ruehmann/mikutter/core/boot/load_plugin.rb:10:in `<top (required)>'
        from /home/ruehmann/mikutter/core/miquire.rb:98:in `require'
        from /home/ruehmann/mikutter/core/miquire.rb:98:in `miquire_original_require'
        from /home/ruehmann/mikutter/core/miquire.rb:95:in `file_or_directory_require'
        from /home/ruehmann/mikutter/core/miquire.rb:76:in `block in miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in `each'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in `miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:18:in `miquire'
        from ./mikutter.rb:40:in `<main>'
```
Thanks,

**Comment by Petitsurume** [comment]
please try update twitter-text gem

**Comment by JPRuehmann** [comment]
Tried that, but did not work.
Deleted it instead, now everything works fine again.
Thanks,
